In [86]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats as scs
from importlib import reload
import pyspark as ps

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [87]:
ratings = pd.read_csv('data/training.csv')
genres = pd.read_csv('data/one_hot_data.csv')

In [88]:
genres.head()

Unnamed: 0  movie_id                   movie_title  year  Animation  \
0           0         1                    Toy Story   1995          1   
1           1         2                      Jumanji   1995          0   
2           2         3             Grumpier Old Men   1995          0   
3           3         4            Waiting to Exhale   1995          0   
4           4         5  Father of the Bride Part II   1995          0   

   Children's  Comedy  Adventure  Fantasy  Romance   ...     Crime  Thriller  \
0           1       1          0        0        0   ...         0         0   
1           1       0          1        1        0   ...         0         0   
2           0       1          0        0        1   ...         0         0   
3           0       1          0        0        0   ...         0         0   
4           0       1          0        0        0   ...         0         0   

   Horror  Sci-Fi  Documentary  War  Musical  Mystery  Film-Noir  Western  
0       0       0            0    0        0        0          0        0  
1       0       0            0    0        0        0          0        0  
2       0       0            0    0        0        0          0        0  
3       0       0            0    0        0        0          0        0  
4       0       0            0    0        0        0          0        0  

[5 rows x 22 columns]

In [89]:
genre_df = genres.loc[:,'Animation':]

In [90]:
genre_names = genre_df.columns

In [91]:
genre_arr = np.array(genre_df)
genre_arr

array([[1, 1, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [92]:
genre_df.rename(columns = {"movie_id":"movie"})
ratings = ratings.join(genre_df, on = 'movie')

In [93]:
genre_sums_df = ratings.groupby('user').sum()

In [94]:
genre_df = genre_sums_df.loc[:,'Animation':]

In [95]:
# genre_df['array'] = np.array(genre_df.loc[:,'Animation':])

In [96]:
user_ids = genre_df.index
genre_array = np.array(genre_df)

In [97]:
genre_array

array([[  4.,  10.,  31., ...,   1.,   1.,   1.],
       [ 16.,  26., 112., ...,  13.,   6.,  12.],
       [  5.,   7.,  31., ...,   6.,   4.,   1.],
       ...,
       [  0.,   1.,   8., ...,   1.,   1.,   1.],
       [  2.,   6.,  40., ...,   9.,   3.,   5.],
       [  9.,  24.,  95., ...,  14.,   9.,  10.]])

In [98]:
genre_by_user = genre_df

In [99]:
np.array(genre_by_user.loc[636])

array([ 4., 10., 31., 11.,  1.,  9., 26., 20., 11., 11., 11., 11.,  1.,
        6.,  2.,  1.,  1.,  1.])

In [100]:
genre_by_movie = genres.set_index('movie_id').loc[:,'Animation':]

In [101]:
genre_by_movie.loc[1]

Animation      1
Children's     1
Comedy         1
Adventure      0
Fantasy        0
Romance        0
Drama          0
Action         0
Crime          0
Thriller       0
Horror         0
Sci-Fi         0
Documentary    0
War            0
Musical        0
Mystery        0
Film-Noir      0
Western        0
Name: 1, dtype: int64

In [102]:
genre_by_user.loc[636]

Animation       4.0
Children's     10.0
Comedy         31.0
Adventure      11.0
Fantasy         1.0
Romance         9.0
Drama          26.0
Action         20.0
Crime          11.0
Thriller       11.0
Horror         11.0
Sci-Fi         11.0
Documentary     1.0
War             6.0
Musical         2.0
Mystery         1.0
Film-Noir       1.0
Western         1.0
Name: 636, dtype: float64

In [103]:
from sklearn.metrics.pairwise import cosine_similarity

In [104]:
cosine_similarity(np.array(genre_by_movie.loc[1]).reshape(1,-1),np.array(genre_by_user.loc[636]).reshape(1,-1))

array([[0.48378707]])

Assume StarRating = B_1.Cos_Sim(movie, user)